### ISSUE TITLE
Date And time caputred incorrectly

### ISSUE THREAD

**Issue by Minal0110** [ABenchM/abm#102]
Date time shown while creating collection is 3:30 pm while it was actually created at 6:30 pm

**Comment by johannesduesing** [comment]
Can you give us the steps that will reproduce this bug ?

**Comment by Minal0110** [comment]
Scenarios & steps to reproduce:
a. Selected 2 jdk projects and clicked on create collection.
b. created jdkcollection at 18:14 on 21st of May 2018 but time shown is 4:12 PM.
Please find attached screen shot of the same.
![java collection](https://user-images.githubusercontent.com/37415168/40317794-cf4021a6-5d22-11e8-8a19-0ddb948df652.png)

**Comment by Minal0110** [comment]
Steps to reproduce:

1. Selected 2 java projects for creating a collection.
2. Created Java collection at 18:12 on 21st 0f May 2018 but time reflected is 4:12 PM which is incorrect.
Please find attached screen shot for same.
![java collection captured with incorrect time of creation](https://user-images.githubusercontent.com/37415168/40318078-bd61cba0-5d23-11e8-9e47-378d45c6ae2f.png)

**Comment by mac24079** [comment]
I looked into the issue and this issue is related to a database table "Collection". Column creation_date has datatype "Date" which should be "DateTime" to capture the correct time. We will have to change in database table collection.

**Comment by mac24079** [comment]
@nguyenLisa @ankur-1989 
Please let me know where do I need to update to reflect the change everywhere as I have updated my local database. It is working fine now.

**Comment by nguyenLisa** [comment]
Yes please. Don't forget to update the installation scripts to reflect the changes.

**Comment by ankur-1989** [comment]
@mac24079 please update abm.sql. I will update the production.

**Comment by mac24079** [comment]
I have updated the abm.sql and generated the pull request #157
