### ISSUE TITLE
clickable disabled button : "Add this project to collection"

### ISSUE THREAD

**Issue by Minal0110** [ABenchM/abm#105]
"Add this project to collection"  button next to select all is shown as disabled but when we click on it will navigates to another page (it is clickable).

**Comment by paulmreese** [comment]
I'd be interested in taking this on!

**Comment by nguyenLisa** [comment]
@paulmreese Sure, feel free to submit a pull request. Thanks for your help!

**Comment by johannesduesing** [comment]
This issue has been moved to the new abm-frontend repository at https://github.com/ABenchM/abm-frontend/issues/31
