### ISSUE TITLE
Newly created version for a collection displayed incorrectly

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm#106]
While deriving a new version for a collection from the current version, the new version is always shown as ‘Derived from version 1: Initial Version ‘, irrespective of the current version. This issue occurs when we derive newer versions while staying on the same page.

Once we navigate to some other page, say the homepage,  and come back to this page, the option to create a newer version is shown as ‘ Derive new version from current version(1)’, even if higher versions exist. Once the newer version is created, the option to create another newer version is displayed correctly, but the newly created version is displayed incorrectly( always shown as derived from initial version)

**Comment by ankur-1989** [comment]
so whenever we landed on this page it starts from version 1, needs modifications to check the length of versions and assigned the latest version.

**Comment by ankur-1989** [comment]
Implemented and pushed to develop branch. Closing this issue as of now.  It can be reopened in case of any issues.
