### ISSUE TITLE
Login screen shouldn't be shown if a user has logged in once. Instead it has to be redirected to the default landing page

### ISSUE THREAD

**Issue by anut347** [ABenchM/abm#111]
Once a user login to ABM application and opens "http://localhost:8080/de.fraunhofer.abm/index.html#/login" in another tab, login screen is shown. But if he clicks on "collections" link in that screen, It takes the user to his/her collections page.

**Comment by ishwaryaPaderborn** [comment]
This issue has been opened in the ABM 2.0 as a new issue #20

**Comment by 24santoshr** [comment]
Closing this issue since it has been opened in the new abm/frontend repository.
