### ISSUE TITLE
Unpinning a collection doesn't make the collection displayed until the page is refreshed.

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm#114]
Unpinning a collection from the pinned collections removes it from there, but the same collection is not shown in the public collections until the page is reloaded again.

**Comment by johannesduesing** [comment]
I'm guessing this has similar reasons as issue #109 .

**Comment by vishaljcj** [comment]
Closing the issue as it is similar to #109

**Comment by johannesduesing** [comment]
This issue has been moved to the new abm-frontend repository at https://github.com/ABenchM/abm-frontend/issues/12
