### ISSUE TITLE
For "Select a Collection" , the drop down is too small 

### ISSUE THREAD

**Issue by anitha181992** [ABenchM/abm#120]
<img width="960" alt="issue abm" src="https://user-images.githubusercontent.com/38462497/39737492-b38c6782-5285-11e8-8d22-0b2dcea336b5.png">
When selected a project, and add it to a project.
The drop down displaying the projects is very minute to be visible for the user.
Since it's an evident feature, its better to have a selection table similar to other tables and  make the selection.

**Comment by bhermann** [comment]
Just to clarify: In your first sentence... Do you mean "add it to a collection"?
Could you also attach a screenshot of the part of the UI. Thanks! 👍

**Comment by nguyenLisa** [comment]
We should keep a drop down. Tables take too much space with unneeded information. I agree that the drop down should be bigger though.

**Comment by anitha181992** [comment]
[https://github.com/ABenchM/abm-frontend/issues/26](url)
Creating it in the abm-frontend , hence closing this issue
