### ISSUE TITLE
Add Bitbucket crawler to the User Interface

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm#127]
Whenever a search is made while adding Projects for creating a new collection, the Project source is always Github, even tough the actual source is Bitbucket or maven.
![issue_reference](https://user-images.githubusercontent.com/23357897/39755053-a9b51d78-52c4-11e8-9807-fe1aa7594445.png)

**Comment by johannesduesing** [comment]
Are you sure this is a real bug ? Because i think what is displayed there are projects working for / with bitbucket, but they are actually hosted on github, so the source would be correct.

**Comment by mac24079** [comment]
Yes , I checked that collections are not coming from BitBucket source. It is  only coming from GitHub. I have checked that code for BitBucket Crawler is there but the calling for the BitBucketCrawler is missing.

**Comment by mac24079** [comment]
Issue fixed and pull request merged.
