### ISSUE TITLE
Automate the password modification in the build system

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm#13]
Automate the build system to include the modification to the passwords before deploying to prod. This should no longer be done by hand.

**Comment by ankur-1989** [comment]
committed the latest changes in automate_password_modification branch where all the configuration are stored in one file under cnd/build.bnd and all the hardcoded tokens and passwords has been removed from the code now. we are not pushing build.bnd file to github.

**Comment by ankur-1989** [comment]
Could not deploy the code because server is not accessible.

**Comment by ankur-1989** [comment]
As part of this ticket following are steps have been taken -
1. Created abm as a service on the abm server  - easy to start and stop.
2. Build has been scheduled for every midnight which will run the build between 12 am to 3 am everyday.

Updating the developer manual.

**Comment by ankur-1989** [comment]
Can we close this ticket now ? we just checked automatic schedule is working fine now.

**Comment by hariharansrc** [comment]
@nguyenLisa Can we mention the file paths used for configuration in the Developer Manual? I am not sure whether to mention the actual server paths.

**Comment by nguyenLisa** [comment]
To be on the safe side, replace the paths by dummy paths (e.g. /path/to/config/file.bnd) in the Developer Manual.
