### ISSUE TITLE
Clicking on any project should open its source repository in another tab.

### ISSUE THREAD

**Issue by Ayybeeshafi** [ABenchM/abm#131]
While selecting projects for creation of a collection, user should be able to open the project on its source repository (e.g Github) to get a better insight of each project. It will help user to make a decision if he/she wants to add that specific project in his/her collection.
![issue](https://user-images.githubusercontent.com/34144308/39894456-3489a0f2-54a7-11e8-8e42-513edec7fdc3.jpeg)

**Comment by janniclas** [comment]
moved to new abm-frontend repository: https://github.com/ABenchM/abm-frontend/issues/9
