### ISSUE TITLE
Build tabs should slide to the right, not to the left

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm#14]
The build status pop-up hide visibility of the elements beneath when they are collapsed on the left. 
They should be relocated to the right. 

<img width="259" alt="capture d ecran 2018-01-26 a 18 40 00" src="https://user-images.githubusercontent.com/1546847/35452857-5958bcf0-02c8-11e8-8248-cbf2af907a1b.png">

**Comment by SwapnilShahGit** [comment]
@nguyenLisa I want to confirm that you mean it should slide from the left side of the screen. So slide from right to left from the left side of the screen.

**Comment by nguyenLisa** [comment]
When collapsed, the tab shows on the left side of the screen (see image). This hides what is beneath. Instead of being placed on the left, the tabs should show on the right. And of course, all animations concerning the tabs should work properly.
