### ISSUE TITLE
Forgot/Reset Password Option can be added as an enhancement

### ISSUE THREAD

**Issue by anut347** [ABenchM/abm#144]
Functionality to handle 'Forgot password' by either asking security questions or sending a reset password link can be taken up as an enhancement.

**Comment by anut347** [comment]
Functionality to handle 'Forgot/Reset password' by either asking security questions or sending a reset password link can be taken up as an enhancement.

**Comment by johannesduesing** [comment]
This issue has been moved to the new abm-frontend repository at https://github.com/ABenchM/abm-frontend/issues/15
