### ISSUE TITLE
Collection name displayed even after deleting the collection in 'Select a Collection' list in 'addtocollection' page

### ISSUE THREAD

**Issue by 24santoshr** [ABenchM/abm#148]
The Collection name is displayed in 'add to collection' page under 'Select a Collection' list even though it has been deleted.

Steps to reproduce:-

i) Create a new Collection.
ii) Delete that Collection.
iii) Search for a project repository in 'search' page. Select any project.
iv) Click on 'Add this project to a collection'/'Add all selected projects to a collection' button.
 v) The deleted collection is still displayed in the 'Select a collection' list.

**Comment by nguyenLisa** [comment]
Where has it been deleted? Can you link to the corresponding commit?

**Comment by 24santoshr** [comment]
![java_1](https://user-images.githubusercontent.com/32432999/40015115-9fbd0036-57b2-11e8-9a88-ee36e5c079fc.png)
![java_2](https://user-images.githubusercontent.com/32432999/40015116-9fe1cdc6-57b2-11e8-8dff-9ccd6fd75c6b.png)
![java_3](https://user-images.githubusercontent.com/32432999/40015117-9ffed7ae-57b2-11e8-816d-755886bc61f4.png)
![java_4](https://user-images.githubusercontent.com/32432999/40015119-a029abf0-57b2-11e8-8c42-d19d7000135d.png)

First screenshot displays a new Collection  created  called 'Java Project'. Second screenshot shows the deletion of that Collection. Third screenshot shows the my updated homepage where the collection 'Java Project' has been deleted. Fourth screenshot shows the Collection name still appearing in  'Select a Collection' list after deletion.

**Comment by 24santoshr** [comment]
moved to new abm-frontend repository: ABenchM/abm-frontend#27
