### ISSUE TITLE
Add crawler for Maven repository

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm#152]
In the about page of the ABM application, it is written that the abm application supports three open-source platforms. But presently, there is no crawler for collecting projects from the Maven repository.

**Comment by mac24079** [comment]
The format of the projects on Maven repository found to be different as from Bitbucket and Github platforms.

**Comment by ankur-1989** [comment]
Yes, it is quite different from them. But you can refer the following link to understand the structure of maven repository. 
https://search.maven.org/#api 
So if you see here on this below link - 
https://search.maven.org/#advancedsearch%7Cgav 
you can search maven repository by multiple options such as -
GroupID 
ArtifactID 
Version Packaging 
Classname 
ShA1-checksum 
You can find the search URLs for each type of search in URL (https://search.maven.org/#api), unlike Bitbucket and GitHub. Even on Github if  you have to search 
for projects user wise you have to give user="required username" filter in the search query. 

Using those URLs given in the link mentioned above, you can get the list of repositories and there is one more link given there using which you can download the repositories but there is a glitch and the problems are - 
1. You will only find jar files but not for all the repositories so need to find to the way -  show only those repositories who have jars available for download.
2. We are maintaining repository information in our repository database table which has a particular structure which you will not find in maven repositories so the information that you can store in maven repositories are like below -

 id                            bigint auto_increment not null,
  link                          varchar(1024),
  parent_link                   varchar(1024),
  path_type                     varchar(1024),
  group_id                      varchar(128),
  artifact_id                   varchar(50),
  artifact_version              varchar(40),
  version                       bigint not null, 
which is completely different with our existing table - two solutions possible 

1. either make a different table 
2. Add columns to an existing table

This is what you will have to check. let me know if you have any doubts.

**Comment by mac24079** [comment]
@ankur-1989 
Looks good, thanks for the info. 
I discussed this with @nguyenLisa and get to know someone has worked before on similar like this. Are there any implementations being done before for this issue, that I can consider or do I need to take this issue and start from scratch?

**Comment by ankur-1989** [comment]
I don't think if somebody has worked for this in ABM. I had started it but could not find useful information so left in between. so you can start from there and let me know if you need any help.

**Comment by nguyenLisa** [comment]
My bad, I confused this with the work Adrian did for Bitbucket last year for an instant. Apologies for the confusion.

**Comment by mac24079** [comment]
@nguyenLisa 
I read the links provided above but didn't found much information and it's a bit time consuming, will look into this may be in the coding phase of the project group.

**Comment by nguyenLisa** [comment]
Sure, that works too.

**Comment by nguyenLisa** [comment]
Builders and crawlers will be taken over by Delphi. No need for that at the moment.
