### ISSUE TITLE
Can't do anything interesting when I log in using my google account

### ISSUE THREAD

**Issue by Delors** [ABenchM/abm#155]
I wanted to create some collection, but I didn't find any option to do so (Safari and Firefox).

**Comment by nguyenLisa** [comment]
Note: when using the login with Gmail.

**Comment by ankur-1989** [comment]
checking. @Delors Are you able to log in to abm application through google account as I am not even able to login thru my google account.

**Comment by ankur-1989** [comment]
Now it is working for me. @Delors Could you please try at your end?

**Comment by nguyenLisa** [comment]
After discussion with @Delors , now working. Closing the issue.
