### ISSUE TITLE
Disable Google login

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm#160]
For the moment, let's disable the Google login capabilities. On the frontend as well (both the new one and the one currently running in prod).

**Comment by nguyenLisa** [comment]
Thanks!

**Comment by nguyenLisa** [comment]
Did you do that in the new frontend as well? And make sure that the backend functionality cannot be triggered with a request to the server?

**Comment by ankur-1989** [comment]
Yes, done in the new front end as well.
