### ISSUE TITLE
Getting org.osgi.framework.BundleException error while building the backend project

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm#164]
![osgi_error](https://user-images.githubusercontent.com/2173927/43520043-e49ccb4c-9591-11e8-85f4-98d21ba4755d.png)

Error scenario: Error occurred while running bnd.bnd after taking latest code

[error_log_build.txt](https://github.com/ABenchM/abm/files/2249301/error_log_build.txt)

**Comment by Chinmay-92** [comment]
@ankur-1989 / @nguyenLisa 
I tried multiple times restarting eclipse / restarting OS but I am getting same error.

Any suggestion to fix this ?

**Comment by ankur-1989** [comment]
check the version of abm.app.auth package is it still available in maven repository or not and similarly for util package

**Comment by Chinmay-92** [comment]
Hi I resolved the issue, reinstalled abm from shell script file.
Closing the issue.
