### ISSUE TITLE
Manage Users (Admin)

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm#166]
The module will include-->manage users
-lock/unlock user account
-change user role

**Comment by nguyenLisa** [comment]
Only the private collections. Public collections will remain accessible to everyone.

**Comment by anitha181992** [comment]
Implemented the update user role for admin.
Branch name: https://github.com/ABenchM/abm/tree/anitha_usermgmt.
Still in progress

**Comment by anitha181992** [comment]
For lock and unlock users
https://github.com/ABenchM/abm/pull/189

**Comment by anitha181992** [comment]
For update role
https://github.com/ABenchM/abm/pull/197

**Comment by anitha181992** [comment]
https://github.com/ABenchM/abm/pull/209

**Comment by Chinmay-92** [comment]
PR merged hence closing the issue
