### ISSUE TITLE
Pending requests API (Admin)

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm#173]
- [x] Admin role validation
- [ ] Approve / Reject pending requests

**Comment by anitha181992** [comment]
@Chinmay-92 : I am working on this 
https://github.com/ABenchM/abm/issues/166
You can remove few of the functionalities mentioned in this issue, since I have made code changes for the issue 166.

**Comment by anut347** [comment]
https://github.com/ABenchM/abm/issues/193 created for second point. I'll take that up.

**Comment by anut347** [comment]
https://github.com/ABenchM/abm/issues/193 created for second point

**Comment by Chinmay-92** [comment]
Pending Issue is moved to #201
