### ISSUE TITLE
Separate ABM from Delphi

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm#18]
We should start separating the ABM part from the Delphi part, starting March/April 2018.
The testing and build systems should also be adapted to make sure nothing breaks.

**Comment by ankur-1989** [comment]
@nguyenLisa 
Can we start working on it? 
I think now the system is stable and everything has been pushed to master as well.

**Comment by nguyenLisa** [comment]
Hi @ankur-1989 , the PG has already started separating ABM from Delphi. Please wait until after April 10th to take over. Once this date is past, we should definitely start with this.

**Comment by ankur-1989** [comment]
Front end part is done. Working on Backend part.

**Comment by ankur-1989** [comment]
Backend part is done. Now ABM only consists of Collection management. It does not consist of following functionalities - Hermes, Collection Build with the different build systems, Projects crawling from GitHub and bitbucket. Changes have been merged into develop branch. Therefore, closing this issue now.
