### ISSUE TITLE
Database changes documentation

### ISSUE THREAD

**Issue by anitha181992** [ABenchM/abm#200]
New changes  to the database for "User profile module"

**Comment by anitha181992** [comment]
@Chinmay-92 
@anut347 
Please review the database document : https://github.com/ABenchM/abm/blob/anitha_adminmgmt/docs/Database_changes.pdf

**Comment by anut347** [comment]
I think in addition to mentioning the db changes made by us, we've to verify DB schema also and update in our wiki page. https://github.com/ABenchM/abm/wiki (DB schema). We can confirm with Lisa once.

**Comment by Chinmay-92** [comment]
@nguyenLisa could you confirm if we can use Wiki page for updated DB schema

**Comment by nguyenLisa** [comment]
Please do. Feel free to open a new page on the wiki for that.

**Comment by nguyenLisa** [comment]
Can you put that in the wiki please? Thanks.

**Comment by anitha181992** [comment]
@nguyenLisa : Chinmay is continuing with the task, so just for a reference I have commented it, he will be updating the wiki:-)

**Comment by anitha181992** [comment]
Wiki page updated, so closing the issue
