### ISSUE TITLE
Properly cancel builds

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm#21]
Builds are not properly canceled when the cancel button is clicked. They re-start at the next run.

**Comment by ankur-1989** [comment]
I tried to reproduce this issue and found what happens actually - 
 When you cancel the build , it cancel the build but does not change the button label , for that you need to close the panel once and come back to panel and then it will show delete button and from there you can delete the cancelled build. 

do we need to change this functionality ? I mean cancel button label should change to delete button without closing the panel ?? and then we should be able to delete the build there only ??

**Comment by nguyenLisa** [comment]
Yes please. When a build is canceled, the UI should automatically go to such a state: 
<img width="1268" alt="capture d ecran 2018-02-05 a 13 47 30" src="https://user-images.githubusercontent.com/1546847/35805300-92e7a552-0a7b-11e8-94ac-5292e453a55e.png">

And when the user clicks on "Show build", they should see something of the sort:

<img width="1262" alt="capture d ecran 2018-02-05 a 13 46 39" src="https://user-images.githubusercontent.com/1546847/35805318-a023663e-0a7b-11e8-8bc5-5b21be376cb2.png">

**Comment by ankur-1989** [comment]
Ii did not get the last part of the comment - as per current set up , cancel build stops the process and when you come back using show build button you see the delete button with stopped processes. 

![image](https://user-images.githubusercontent.com/24721077/36066561-02b09df6-0eac-11e8-8dbe-99f9227e1a9b.png)

**Comment by nguyenLisa** [comment]
Yes, the last part already exists. Just make sure you keep it that way.

**Comment by ankur-1989** [comment]
I tried one more scenario -
So if you cancel the build after docker image creation so it cancel the building and successfully deleted the docker container and image which is required so this part is also working fine.

**Comment by ankur-1989** [comment]
After changes what it does is -
1. Build the version
2. modal window will open and will start the process.
3. On click of cancel build , it will cancel the process and will close the connection and close the panel.
4. On reopen the panel , we will see delete button and close button.
5. Using delete button , we can delete the cancelled repository.

Is this procedure expected ?

**Comment by ankur-1989** [comment]
i did some changes now it is not happening.

**Comment by nguyenLisa** [comment]
Great! Can you push your changes?

**Comment by ankur-1989** [comment]
pushed the changes and now working fine.Hence closing the ticket.
