### ISSUE TITLE
Email api for Approve/Reject requests

### ISSUE THREAD

**Issue by anitha181992** [ABenchM/abm#212]
Email api used for admin for approving and rejecting the user request for registration

**Comment by anitha181992** [comment]
https://github.com/ABenchM/abm/pull/213

**Comment by anut347** [comment]
https://github.com/ABenchM/abm/pull/223

**Comment by anut347** [comment]
https://github.com/ABenchM/abm/pull/237
made few changes and now mail is sent. verified.
