### ISSUE TITLE
Integrate Zenodo

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm#24]
Collections should no longer be saved on our server, but on Zenodo.

**Comment by ankur-1989** [comment]
Configurations related to tokens and service in frontend is completed.But, there is some problem with ZenodoClient class as bnd is not able to import the zenodoClient class. Tried several methods but all are failing, maybe need to change the approach in the implementation of ZenodoAPI package.

**Comment by bhermann** [comment]
Can you give more details on the problem? Error messages, etc.

**Comment by ankur-1989** [comment]
As part of Zenodo Integration, I was writing a Controller which is a rest endpoint. 

We generally use @Reference annotation to register the service in controllers, So I did. But, it is giving the following error - 
! Failed to start bundle de.fraunhofer.abm.app-1.0.0.201902161253, exception Could not resolve module: de.fraunhofer.abm.app [7]
  Unresolved requirement: Import-Package: de.upb.cs.swt.zenodo
2. When I tried to use it directly on importing the package and creating a new instance.  It gives the same error.
org.osgi.framework.BundleException: Could not resolve module: de.fraunhofer.abm.app [7]
  Unresolved requirement: Import-Package: de.upb.cs.swt.zenodo

3. I tried to use different configurations for OSGi but then it was not able to register the method on build and was not able to find main class.

**Comment by bhermann** [comment]
I'm not quite familiar with bnd itself, but know a bit about OSGi in general. Currently, we have packaged the API library as a Maven artifact. Is that enough or do we need to prepare more for it to be included.

**Comment by ankur-1989** [comment]
Zenodo has been integrated with ABM and in master branch now. We can create a deposition on Zenodo now. To upload an archive to Zenodo for a particular version, we need artifact file from delphi and the discussion is pending for the same.

**Comment by ankur-1989** [comment]
After discussion, We came to a conclusion that we will parse the project urls in a collection and will download the corresponding jar and will zip all the jar files in a version and will upload it to zenodo.

**Comment by ankur-1989** [comment]
Zenodo Integration is finished.

**Comment by ankur-1989** [comment]
Closing this issue now. Token generated for Sandbox for ABM github user.
