### ISSUE TITLE
Delete collection by version

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm#240]
- [x] Implement API to delete a version on the basis of Collection ID and version ID as inputs.

- [x] If only 1 version is present, delete the collection as well.

**Comment by anitha181992** [comment]
This functionality is already existing in the application

**Comment by Chinmay-92** [comment]
If only 1 version is present, delete the entire collection as well ?

**Comment by Chinmay-92** [comment]
closing this issue
