### ISSUE TITLE
Redesign the Collection view page

### ISSUE THREAD

**Issue by SwapnilShahGit** [ABenchM/abm#25]
The current view looks like this: 
<img width="1418" alt="screen shot 2018-01-26 at 8 41 36 pm" src="https://user-images.githubusercontent.com/11033960/35467181-5c490972-02d9-11e8-90fa-835ff8b7065d.png">

The goal is to redesign as the following: 
![download](https://user-images.githubusercontent.com/11033960/35467185-6d128f44-02d9-11e8-8973-ddda1f851d34.png)

Any feedback on the design is appreciated! Additional features will be added as development progresses.

**Comment by nguyenLisa** [comment]
The proposed redesign has several usability issues that were listed during the code sprint. Please detail them here before you start coding.

**Comment by SwapnilShahGit** [comment]
So in terms of the white space, I feel that the information is optimally organized in a logical manner. I feel categorizing the information and creating a horizontal table of sorts can help the user read the information easier. What are your thoughts?

I feel that was the largest criticism of the design. I will go through the notes once again and read the feedback.

**Comment by nguyenLisa** [comment]
The whitespace is an important concern in the design of the UI, but the most important issue in this interface is the lack of information given in the bottom table. See the detailed feedback below. Next time, please detail the entire list of issues that were discussed in your message.

Also, the prototype is incomplete. I would like to see how the UI looks like when the different options are run: when the collection is built, modified, etc. Please provide a complete prototype. 

- White space: There is too much white space in the proposed version of the design. In the Collection Information and Build Information sections, 2/3 of the horizontal space is useless.
- Collection Information and Build Information: 
  - The column for that is too narrow. How will it behave if a collection has a long name or description?
  - The information is not consistent between the two sections. Why have a created date for one of them and a created date and time for the other?
  - Can we save space by having the created date and time on the same line?
  - Unlike the original UI, the user has to make the extra effort to click on the wrench and see a new UI component to modify the name and description information. Why not make the editable information directly editable?
- Wrench icon: The placement of the wrench takes vertical space and creates useless whitespace. Also what does it allow to modify? The Collection information? The Build information? Something else? Would it be possible to get rid of it by bringing the editable information directly in the main interface?
- "Options" drop-down:
  - What does it do?
  - What does it apply to? 
    - The entire collection? In this case, it would make sense to integrate the functionalities of the wrench icon into the Options drop-down, and bring the drop-down up into the design to make it clear that it applies to the entire collection and not just one build.
    - Only one particular build? In this case, please make the actionable functionalities consistent between the Collection information and Build information section: one is accessed with a wrench icon, the other, through the Options drop-down.
- The default choice in the "Select Build" drop-down is useless information. It is a better design to directly show the selected build information in the drop-down.
- The search bar needs to be separated from the table by a bit of whitespace. Additionally, sorting options can be implemented in the table headers to help with the navigation.
- The table contains minimal information:
  - The purpose of the table is not only to display the list of projects contained in the collection. It is also to help users add and remove projects from it. With the UI elements shown in the prototype, the user is unable to do that. Please complete the prototype to show how the user should interact with the table to achieve all of the desired features of the page.
  - The name and commit id can be useful, but it is hardly enough to allow the user to choose which kinds of projects they already have in the collection and which they still need or have in duplicate, w.r.t. their own criteria. For example, if I want a project in Java, a project in C++ and one in JavaScript, I am unable to see this in the current interface. Such information should be shown in the table in a smart way, to not cluster the information.

The last point in particular needs careful thinking and design. It is the most important part of the UI of the entire UCOSP project and should be designed by the entire group together. One way of improving the table is to incorporate the modal Hermes filter dialog into the table. I'll be adding @tylerpav and @alexli123 to the issue.

**Comment by nguyenLisa** [comment]
Closing this issue: it will be worked on through other issues.
