### ISSUE TITLE
PostUserName method was not able to handle null password updation - User Profile.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm#268]
PostUserName was giving an error because it was not able to handle a null password. Moreover, New user creation method should be different from update user as per the current coding style. Therefore, need to separate post request from put request.

Now, Save changes and update password buttons are independent of each other.

It can be found here: 
https://github.com/ABenchM/abm/commit/3d3c844d06c72f4dd369cd4ea9030c1d4b9dd2ed

**Comment by Chinmay-92** [comment]
@mac24079 is this issue still open ?

**Comment by mac24079** [comment]
Submitted it here https://github.com/ABenchM/abm/commit/3d3c844d06c72f4dd369cd4ea9030c1d4b9dd2ed . Hence, closing this one.
