### ISSUE TITLE
When deleting a user from User-profile functionality - error coming

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm#269]
There is a need to change the postDeleteUser to deleteusername as post request was giving some parsing illegal character error even if I was passing the data in a correct format, so after changing it to the new format when I tried to delete the user it started giving me the below-attached error. 

![delete_user](https://user-images.githubusercontent.com/23357897/49072118-d5d9b700-f22f-11e8-9811-754d4ba82828.png)

**Comment by mac24079** [comment]
@anut347 
Any updates?

**Comment by anut347** [comment]
Hi Mohit, This is probably because there was an entry for this user in the reset_tokens table which i forgot to consider. The necessary code changes are made. I'll create a pull request for the same by tonight and try to merge the code in abmpgdevelop so that you can check. I've also changed the deleteUsername function name as required which will also be pushed by tonight hopefully.

**Comment by anut347** [comment]
Pull request created for the same.
https://github.com/ABenchM/abm/pull/284

**Comment by mac24079** [comment]
@anut347 
I still do not see the request merged into abmpgdevelop branch, so can't check at the moment. Also, please write here the name of the method that I should call for the change. 

Thanks.

**Comment by anut347** [comment]
You can use deleteUsername for this. Regarding merge, Chinmay will be speaking to Lisa. Since the abmpgdevelop branch is locked now and code can be merged only if two people approve the pull request.

**Comment by Chinmay-92** [comment]
what the status on this issue ? @mac24079 & @anut347

**Comment by anut347** [comment]
changes for delete username is done and committed to abmpgdevelop. testcase is still to be pushed. I couldn't integrate and test with frontend since i was getting error in my stsyem that dist folder does not exist. @mac24079 couold you please check?

**Comment by mac24079** [comment]
@anut347

All the changes are in the frontendpg branch for this functionality for the frontend part.  Please check once at your end,  if some error is coming as stated above please share a screenshot for the same so I can look into.

Thanks.

**Comment by anut347** [comment]
Addressed in https://github.com/ABenchM/abm/pull/301
