### ISSUE TITLE
One email for one user.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm#270]
At present, in the application, there is a feature where the userName is unique and different users can have the same email id. To make things simple, the application will now allow that one user can have only one e-mail and the same e-mail which has been used once cannot be used any further. But the e-mail can be changed/updated (like in my-profile module)so we will not keep the e-mail id as the primary key.

**Comment by nguyenLisa** [comment]
Thanks @mac24079 , this will be much easier to handle.

**Comment by anitha181992** [comment]
@nguyenLisa: As per discussion with @mac24079 ,for resetting the password, we decided to  consider only the username to be entered by the user, which is already a primary key. So the issue gets resolved without worrying about the different users entering the same email id.

**Comment by mac24079** [comment]
That means when we are resetting the password we should reset just with the user name. May be I got confused a little.

@anitha - We are done with the resetting password functionality implementation. Sorry for the inconvenience.  We just need to make sure there is only one email for one user.

Thanks

**Comment by anitha181992** [comment]
This issue can be closed as it is resolved

**Comment by nguyenLisa** [comment]
Thanks @anitha181992. Could you reference the commit that solves the issue?

**Comment by mac24079** [comment]
Just encountered this while cleaning up the issues from the back-log.

@anitha181992 Is it done?

**Comment by mac24079** [comment]
This is not working in the develop branch.

Hence, reopening this one.

**Comment by anitha181992** [comment]
It was discussed that we should keep only the user ID should be unique, the email cannot be unique for a user, so we implemented the reset password functionality using the username not the email ID, so this functionality was never implemented.

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm/pull/337.

Hence, closing.
