### ISSUE TITLE
User-email functionality missing for resetting password. 

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm#271]
At the moment (in abmpgdevelop+frontendpg branch), there is a functionality which is working well for resetting the password of a user (only thorugh Username) when a user clicks on the forgot-password feature/link.

This needs to be taken care of as we need that a user can reset the password both via username and e-mail.

Reference issue #270 .

**Comment by mac24079** [comment]
@anitha181992 

I am mentioning you here as you were taking care of this part. Now, it is little simple as we will be allowing only one email for one username. Would you like to take this as we are near to the end date of the milestone? or you want me to take it and finish it.

Thanks.

**Comment by mac24079** [comment]
@anitha181992 
do we need this one ?

**Comment by mac24079** [comment]
@anitha181992 
Any updates?

**Comment by anitha181992** [comment]
@mac24079 : I am not sure why this issue was created, as we had decided that we will use username for changing password. So I guess we need to have a discussion with the team and know the requirements.
I wouldn't be able to decide on that

**Comment by mac24079** [comment]
@anitha181992 
This issue was opened when we spoke that it is needed and how we will pass the email with the tokens when an emil will be sent to the user for resetting the password(PG meeting). Though we get the clarifications from @nguyenLisa afterwards (can be found here:https://github.com/ABenchM/abm/issues/270#issuecomment-442055528.) and for the same I thought to ask you once finally before closing the issue.

Hence, closing this ticket and will be reopend if needed.
