### ISSUE TITLE
Update Password for User Profile functionality

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm#272]
At present, the updatepassword functionality is updating the password but when logging in with the updated password it doesn't allow the user to log in.

What is happening as per my observance: You can also find the attached figure after the end of text.

1. User profile page exchanges the data with the User table in the database. So when I update the password in the database it updates the password in the user table.

2.  But, when it authenticates the credentials for login, it seems it authenticates through role_properties table.

**As a solution,** either we should update the role_properties table as well or we should authenticate the login functionality through the user table.

![db_structure_reference](https://user-images.githubusercontent.com/23357897/49117579-761bf400-f2a1-11e8-9d1b-a857c19f29e1.jpeg)

**Comment by mac24079** [comment]
@anut347 
Can you please confirm if I am wrong here, or we can follow the above solution or some other approach that you have written and I am not getting?

Thanks.

**Comment by anut347** [comment]
@anitha181992 > Pls comment

**Comment by anut347** [comment]
Hi Mohit,

yes. It"s not updating the role properties table as of now . I"ll make the necessary changes in sometime and push it to abmpgdevelop first.

**Comment by mac24079** [comment]
Hello @anut347,

Sounds good. Since you are in the university network please test the front-end part and let me know the changes that I should include the front-end part. Like to call any services etc.

Thanks.

**Comment by mac24079** [comment]
Also, please do the needful for the issue #269 .

Thanks.

**Comment by anut347** [comment]
https://github.com/ABenchM/abm/pull/277

**Comment by mac24079** [comment]
@anut347 

any updates on this? As the code has not yet pushed to abmpgdevelop branch.

**Comment by anut347** [comment]
We're facing some issue since none of us are able to find the enabled merge button. Will sort this out by tomorrow.

**Comment by anut347** [comment]
Hi Mohit, Code changes are in abmpgdevelop branch now

**Comment by mac24079** [comment]
@anut347 
Could you please tell the name of the method and file I should consider checking this functionality.

Thanks.

**Comment by anut347** [comment]
You can use putUsername. This would be done as part of updating user profile. Correct me if I'm wrong.

**Comment by anut347** [comment]
Fixed in https://github.com/ABenchM/abm/pull/305
