### ISSUE TITLE
Wrong values inserted into 'role_members' table while registration

### ISSUE THREAD

**Issue by vishaljcj** [ABenchM/abm#288]
after registration, role_members table is getting populated incorrecctly.
![image](https://user-images.githubusercontent.com/37999970/50056256-e22fa080-0159-11e9-85bb-5260e396534e.png)

**Comment by nguyenLisa** [comment]
Could you specify what is going wrong exactly? Thanks!

**Comment by vishaljcj** [comment]
The value which should be inserted into member_member is inserted into member_parent and the value should be inserted into member_parent is being inserted into member_member.

**Comment by Chinmay-92** [comment]
this seems to be "Not an issue"
role_members table should have member_parent as first column and member_member as second column.

Hence, closing the issue for now.

**Comment by anut347** [comment]
we can change JdbcRoleDao.java insert statement specifying the column names also in the insert SQL to be sure that this won't happen. I'll make changes and create a pull req.

**Comment by anut347** [comment]
https://github.com/ABenchM/abm/pull/290 for abmpgdevelop
https://github.com/ABenchM/abm/pull/291 foe develop

**Comment by Chinmay-92** [comment]
what's the status on this issue?
