### ISSUE TITLE
Forget Password Link is throwing exception - in abmpgdevelop branch.

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm#295]
@anitha181992 

When resetting a password via Forgot Password link, it is throwing some error, can you please tell me if I am missing some stuff once after checking as per my remembrance this was working well sometimes before. This error was coming in @vishaljcj PC as well. 

Error Front-end:
![image](https://user-images.githubusercontent.com/23357897/50545755-70f0f280-0c1b-11e9-83c4-79ca9b29a923.png)

Error back-end:
![image](https://user-images.githubusercontent.com/23357897/50545729-d1cbfb00-0c1a-11e9-9603-10a12542093c.png)

Branches used:
For back-end part: abmpgdevelop
For front-end part: frontendpg branch.

Please let me know if I am missing something here or some method names have been changed.

Thanks.

**Comment by anitha181992** [comment]
@mac24079 : Nothing was changed from the last commit, I actually copied your code changes last commit back into the abmpgdevelop branch. I have passing test cases. The error usually occurs when the methods name do not match the required format, but nothing has been changed.

**Comment by mac24079** [comment]
Can you mention the commit changes/id here that you have copied? I am aware of the error that is coming but what I can see is the 500 error is from the back-end part. I can check tough but it may take time as presently I am on travel and have limited access to the laptop and communicating here via Mobile so can't easily see the changes you are referring. In case not, then I'll look it into once after the first week of Jan 2019.

Thanks.

**Comment by anitha181992** [comment]
There was a problem with the URL endpoint, mentioned in the controller,changes are made and merged into develop
