### ISSUE TITLE
getversiondetailsbyId api

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm#299]
This api should return all the version details along with the collection id, collection name and owner of the collection from collection table.

**Comment by Chinmay-92** [comment]
PR #328 is merged
@anut347 - please close the issue if it's finished

**Comment by vishaljcj** [comment]
@anut347 I tested this and the getVersionDEtails() method in the VersionController returns all the versions irrespective of the versionID passed. It should return only the version that is associated with the versionID passed, along with the collection details. So ideally there should be only one VersionDTO object inside the CollectionDTO.

**Comment by anut347** [comment]
Hi. Fixed issue in branch https://github.com/ABenchM/abm/tree/anu_get_milestone4.
PR Created for the same https://github.com/ABenchM/abm/pull/330.

**Comment by anut347** [comment]
PR merged and confirmed with Vishal. Hence closing this issue.
