### ISSUE TITLE
Mail for Approve/Reject

### ISSUE THREAD

**Issue by anut347** [ABenchM/abm#319]
Mail should be sent when admin approves or rejects a user.
Corresponding code changes are in PR https://github.com/ABenchM/abm/pull/313.
It works for me from uni network. But @ankur-1989  is facing some issues with the same. Not sure of the exact issue.

UserApprovalController.java (Line no. 92 and 96)

**Comment by Chinmay-92** [comment]
merged in [https://github.com/ABenchM/abm/pull/313](https://github.com/ABenchM/abm/pull/313) hence closing the issue
