### ISSUE TITLE
Test case null pointer exception

### ISSUE THREAD

**Issue by anut347** [ABenchM/abm#327]
- when i open CollectionControllerTest.java and run test I'm getting null pointer exception in delete in testCollectionById
- null pointer exception at collectionController.java line number 175 when running test case CollectionControllerTest.java
- delete in testCollectionById fails

Branch : https://github.com/ABenchM/abm/tree/anu_get_milestone4
Related to issue: https://github.com/ABenchM/abm/issues/299 ( The test case failing is not because of any new code changes)

**To Reproduce**

**Expected behavior**
All test cases should pass

**Additional context**
As per Ankur and Chinmay that it takes the first collection always.

Assigning this to @Chinmay-92  since he was looking into delete collections

**Comment by anut347** [comment]
@Chinmay-92 :Please suggest

**Comment by anut347** [comment]
I deleted the entire DB and 'testCollectionById' test runs successfully.

**Comment by anut347** [comment]
https://github.com/ABenchM/abm/pull/328

**Comment by Chinmay-92** [comment]
merged, hence closing
