### ISSUE TITLE
Issue with ABM installation script not installing properly

### ISSUE THREAD

**Issue by iamebuka** [ABenchM/abm#329]
**Describe the bug**
When you try to install ABM using the installation script that is part of the ABM git Repo, While the Installation completes, some key parts of the installation are never installed; The password for the MySQL database never gets assigned to the root user, also Ubuntu and the docker images as defined in the docker compose files are not installed

**To Reproduce**
1. Clone the ABM repository from git to a directory on your local computer
2. Navigate to the folder ABM > docs > abm_install
3. run the abm_install.sh script
4. After installation, log into MySql from bash
5. see the error 
6. Also, when you run the command "docker images" on your terminal after installation, notice required images weren't installed. 

**Expected behavior**
The script is supposed to set up the ABM environment; install MySQL and create the default root user with a password, install docker and the images as defined in docker compose.

**Comment by Chinmay-92** [comment]
is this issue resolved? we can close it

**Comment by iamebuka** [comment]
@Chinmay-92 no, it isnt resloved

**Comment by ankur-1989** [comment]
The issue has been fixed now. 
@nguyenLisa 
I have tested the script once. Do you want someone also to test the script?

**Comment by nguyenLisa** [comment]
The changes create issues in the tutorial here: https://github.com/ABenchM/abm/blob/master/docs/Developer_Manual.md

The new installation scripts do not download ABM anymore, so they require the user to clone ABM on their own, which is not explained here: https://github.com/ABenchM/abm/blob/master/docs/Developer_Manual.md#installation-scripts-linux-only.

As a result, this renders all mentions of "${DIRECTORY}" in the tutorial wrong.

Can you please fix this? Thanks.

Otherwise, the script seems to be working fine. I had no docker issues, nor sql issues.

**Comment by ankur-1989** [comment]
@nguyenLisa 
I have fixed the tutorial. Please check once and let me know if you find something missing. I will close the ticket after confirmation.
Thanks!!

**Comment by nguyenLisa** [comment]
Hi,

There are still some references to "${DIRECTORY}", that should be adapted so that it works.

Also, could you add the commands for installing git and cloning the repo directly at the start of the installation script section? 

Thanks.

**Comment by ankur-1989** [comment]
@nguyenLisa 
Added the commands for repo cloning and git installation. 

Regarding ${DIRECTORY} , it is mentioned in the manual installation set up and I believe it should be there. I have removed the references in the Installation script section.

**Comment by nguyenLisa** [comment]
Oh, my bad. Thanks then!
Could you add a README at the root at the repo that points to the developer manual and the user manual? Then, feel free to close the issue.

**Comment by ankur-1989** [comment]
Done.
