### ISSUE TITLE
Admin should not be listed in manger user table

### ISSUE THREAD

**Issue by Minal0110** [ABenchM/abm#331]
On ABM UI, admin name should not appear on manage user table. to prevent admin from locking, deleting itself from ABM application.

1. Login to ABM website as a admin and click on manage user page to check if admin name is visible in mange user list.

**Expected behavior**
Admin name should not appear in manage user table.

Below is the screenshot of mentioned bug
![admin listed on manage user](https://user-images.githubusercontent.com/37415168/53178847-edd49300-35f2-11e9-9533-47726a179b9b.png)

**Comment by anut347** [comment]
Changes made and PR created https://github.com/ABenchM/abm/pull/332

**Comment by mac24079** [comment]
Merged with https://github.com/ABenchM/abm/pull/332 .

Hence, closing.
