### ISSUE TITLE
Issue building abm after migration steps

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm#338]
I have followed all steps given
Clean all projects, restarted eclipse still nothing is fixing the error.
Noone else in ABM PG could finish migration steps

Below are the errors after clicking Run OSGI: ( No compilation errors were there )

Status ERROR: bndtools.core code=0 Cannot find /error/com.jcraft.jsch;version=0 Not found in [bnd-cache [/home/chinmay/Documents/abmbackend/abm/bnd-workspace/cnf/cache/4.1.0/bnd-cache r/w=false], MavenBndRepository [localRepo=/home/chinmay/.m2/repository, storage=Central, inited=true, redeploy=false], Local, Release, MavenBndRepository [localRepo=/home/chinmay/.m2/repository, storage=Apache, inited=true, redeploy=false], Distro [/home/chinmay/Documents/abmbackend/abm/bnd-workspace/cnf/cache/4.1.0/Distro r/w=false]] null

Status ERROR: bndtools.core code=0 com.jcraft.jsch;version=0 Not found in [bnd-cache [/home/chinmay/Documents/abmbackend/abm/bnd-workspace/cnf/cache/4.1.0/bnd-cache r/w=false], MavenBndRepository [localRepo=/home/chinmay/.m2/repository, storage=Central, inited=true, redeploy=false], Local, Release, MavenBndRepository [localRepo=/home/chinmay/.m2/repository, storage=Apache, inited=true, redeploy=false], Distro [/home/chinmay/Documents/abmbackend/abm/bnd-workspace/cnf/cache/4.1.0/Distro r/w=false]] null

**Comment by Chinmay-92** [comment]
If I click continue anyway button then below is the error stack

Failed to start bundle de.fraunhofer.abm.scm.git-1.0.0.201903071033, exception Could not resolve module: de.fraunhofer.abm.scm.git [18]
  Unresolved requirement: Import-Package: org.eclipse.jgit.api; version="[4.4.0,5.0.0)"
    -> Export-Package: org.eclipse.jgit.api; bundle-symbolic-name="org.eclipse.jgit"; bundle-version="4.4.0.201606070830-r"; version="4.4.0"; uses:="org.eclipse.jgit.revwalk,  org.eclipse.jgit.treewalk.filter,  org.eclipse.jgit.diff,  org.eclipse.jgit.util,  org.eclipse.jgit.notes,  org.eclipse.jgit.dircache,  org.eclipse.jgit.api.errors,  org.eclipse.jgit.lib,  org.eclipse.jgit.treewalk,  org.eclipse.jgit.blame,  org.eclipse.jgit.submodule,  org.eclipse.jgit.transport,  org.eclipse.jgit.merge"
       org.eclipse.jgit [106]
         Unresolved requirement: Require-Bundle: com.jcraft.jsch; bundle-version="[0.1.37,0.2.0)"


Failed to start bundle org.eclipse.jgit-4.4.0.201606070830-r, exception Could not resolve module: org.eclipse.jgit [106]
  Unresolved requirement: Require-Bundle: com.jcraft.jsch; bundle-version="[0.1.37,0.2.0)"

**Comment by Chinmay-92** [comment]
I think I have figured out issue
I forgot to rename the jar, closing the issue

**Comment by Chinmay-92** [comment]
If I choose to continue anyway after this error, the server is running properly with the above errors in console.

**Comment by ankur-1989** [comment]
@Chinmay-92 
Step for downloading jcraft package and replacing it with exisiting one might be missing. Therefore, it is coming. Please check otherwise we can meet on Monday.

**Comment by ankur-1989** [comment]
@Chinmay-92 Shall I close this issue then?

**Comment by Chinmay-92** [comment]
Yes we can close this issue
