### ISSUE TITLE
Private collections should now be "My collections"

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm#36]
- [x] In the "Collections" tab, rename "Private collections" to "My collections".
- [x] Include in "My collections" the list of public collections that have been created by the user.
- [ ] Add a column in the "My collections" table that contains a button "Make public" if the collection is private, and a "Pin collections" if the collection is public.

**Comment by tylerpav** [comment]
First two checkboxes are done as requested by Lisa on slack (not pushed yet); will see if third can be finished as well.

**Comment by nguyenLisa** [comment]
Great! Before pushing, please make sure that you test the changes (everything works well and nothing broke) on the latest version of the code (sync your branch with the master).

**Comment by tylerpav** [comment]
closing issue and made new issue #85 for part 3
