### ISSUE TITLE
The project rows on a collection's page should link to the URL of the repository

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm#49]
In a collection's page, the list of projects belonging to a collection are shown in a table. Each row of the table should:
- [ ] be clickable and link to the URL of the project's repository, with the right commit.
- [ ] show a clickable cursor on mouse hover.

**Comment by johannesduesing** [comment]
This issue has been moved to the new abm-frontend repository at https://github.com/ABenchM/abm-frontend/issues/9

**Comment by nguyenLisa** [comment]
Closing because it was moved.
