### ISSUE TITLE
my.htm and editCollection.htm are duplicates

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm#50]
Why is my.htm used?

**Comment by ankur-1989** [comment]
Need to check, I never created it. need to check if it is really getting used

**Comment by ankur-1989** [comment]
we are not using my.html anywhere , may be somebody created it for testing. I'll delete it and will commit the latest one in master branch. we need to make sure things created for testing purpose should not be committed in master branch.

**Comment by nguyenLisa** [comment]
I can see it being used here https://github.com/ABenchM/abm/blob/master/bnd-workspace/de.fraunhofer.abm.app/web/controllers/CollectionController.js#L144 and there https://github.com/ABenchM/abm/blob/master/bnd-workspace/de.fraunhofer.abm.app/web/controllers/CollectionController.js#L161
Is that an error?

**Comment by nguyenLisa** [comment]
From what I am seeing in the history, my.htm was the original page for editing a collection. Five months ago, @ankur-1989 created the editCollection.htm. Do you remember why you did that instead of reusing my.htm?

**Comment by ankur-1989** [comment]
Yeah Now I remember , Do you remember we used to have MyCollections page earlier so then we had this page my.html but later alex restructured the application and after that we had replaced the mycollection page with edit collection page. So now there is no mycollection page but my.htm still exist and it is getting called at some places. I replaced the calling of /my with editCollection and tested the application it is working fine. I'll commit the changes and will deploy in production with other changes in one go.

**Comment by ankur-1989** [comment]
It is commented at some of the places but he might forgot to change it at some places.

**Comment by nguyenLisa** [comment]
Ok, thanks for looking into it. Feel free to close the ticket! :)

**Comment by ankur-1989** [comment]
Sure i'll close this ticket now.
