### ISSUE TITLE
Set up Skeleton Html for EditCollection Page

### ISSUE THREAD

**Issue by SwapnilShahGit** [ABenchM/abm#54]
**Buttons** 
- [x] Delete Collection
- [x] New Version
- [x] Make Public
- [x] Delete Version
- [x] Save Changes
- [x] Edit Project(s)
- [x] Download Results

**Text boxes**
- [x] Collection Name
- [x] Collection Description

**Drop downs**
- [x] Build Name

**Charts**
- [x] Project Chart
- [x] Name Column
- [x] Commit Column
- [x] Add/Remove Filters Column

**Comment by SwapnilShahGit** [comment]
Please also refer to: https://docs.google.com/document/d/1sGTa4tlajKHZg5M_0_UTXI5HYDEQFhOCKJ-moYOzF9s/edit

Alongside, the feedback by Lisa in the "20180302" meeting minutes: 
https://docs.google.com/document/d/10bnSZtqJJ83Rs8xM8C06oJYeQ7H1FNiLroYWfOkVowI/edit#

**Comment by SwapnilShahGit** [comment]
From mockup for reference: 
<img width="734" alt="skeleton" src="https://user-images.githubusercontent.com/11033960/36942054-1fc1ba64-1f38-11e8-897a-12de387fee06.png">

**Comment by nguyenLisa** [comment]
After the discussions of the last meeting, the mockup is no longer up to date. Please update it.
- [ ] Description box to the right of the collection information.
- [ ] Build information beneath the Collection information.
- [ ] Build information layout: horizontal.
- [ ] Horiontal separator between the Collection and Build information.

**Comment by SwapnilShahGit** [comment]
Feedback from Lisa:
(1) "Description" should be horizontally aligned with "Collection information". 
(2) "Decription", "Collection information" and "Build information" should be aligned left. 
(3) "Collection information" and "Build information" should be shown in a bigger font. 
(4) The font of the whole page (except the buttons and table) seems to be bold. This should *not* be the case. Please be consistent with the rest of the website and use the same font. 
(5) The "Collection information" and "Build information" sections should have a bigger line spacing. This looks quite cluttered. 
(6) The "Description" box and the table should be vertically aligned on the left. 
(7) the buttons in the "Collection information" and the "Build information" should be placed similarly: 
    (a) if one has a two-column-column (or single) layout, the other one should have it too. 
    (b) all of the "Delete" buttons should have the same design: if one has a trash can icon, the other one should have as well. 
    (c) The placement of the buttons should mirror each other: if the delete button is first in the "Collection information", it should be first in the "Build information".

**Comment by tylerpav** [comment]
Will put some/most of these in and hopefully be able to screenshare tomorrow - worse case will provide a screenshot so we can discuss.

**Comment by tylerpav** [comment]
Posted screenshot to slack for approval

**Comment by SwapnilShahGit** [comment]
![image](https://user-images.githubusercontent.com/11033960/37811460-c41e9526-2e30-11e8-839e-c6562b23f556.png)

Uploading updated skeleton page for reference.

**Comment by SwapnilShahGit** [comment]
" Add/Remove Filters Column" will be done in #68, closing.
