### ISSUE TITLE
dynamically get build information 

### ISSUE THREAD

**Issue by SwapnilShahGit** [ABenchM/abm#56]
work off #54 and use existing code

**Comment by tylerpav** [comment]
Current items in:
- [] Name - currently has the old version dropdown in. Are versions now going to be named? Or is it still version x? Should this dropdown have versions that are public?
- [x] Creation Date 
- [ ] Latest Version Built - If this label is accurate doesn't it make more sense for it to be in collection info? or is it supposed to be 'last time version was built'
- [x] Privacy

**Comment by SwapnilShahGit** [comment]
Closing this issue as the relevant changes have been made and the rest are enhancements for the future that are not in the scope of the UCOSP course.

**Comment by nguyenLisa** [comment]
Ok for closing this issue, but please open new ones with the remaining todos for the future.
