### ISSUE TITLE
generate logic for when buttons should be enabled/disabled

### ISSUE THREAD

**Issue by SwapnilShahGit** [ABenchM/abm#57]

**Comment by tylerpav** [comment]
Save Changes:
- [ ] Disabled when Name is empty
- [ ] Disabled when building
Delete Collection
None
New Version:
None
Make Public:
- [ ] Disabled when version is public
- [ ] Disabled when building ???
Delete Version:
- [ ] Disabled when version is public
- [ ] Disabled when building ???
Edit Project(s):
- [ ] Disabled when version is public
- [ ] Disabled when building ???
Download Hermes Results: 
- [ ] Disabled when there are no builds/versions in collection
- [ ] Disabled when building ???

All Buttons disabled when page is loading/saving
