### ISSUE TITLE
implement delete collection button

### ISSUE THREAD

**Issue by SwapnilShahGit** [ABenchM/abm#59]
- create alert to ensure user wants to delete collection

**Comment by SwapnilShahGit** [comment]
From mockup for reference: 
<img width="204" alt="delete_verification" src="https://user-images.githubusercontent.com/11033960/36942055-2bb543cc-1f38-11e8-8a23-86c0df0c5ffa.png">

**Comment by tylerpav** [comment]
Alert added as confirm, so doesn't have the exact same layout as above.

**Comment by tylerpav** [comment]
After a meeting was discussed that should redirect you back to homepage, added that code.
