### ISSUE TITLE
implement new version feature [Hermes Modal]

### ISSUE THREAD

**Issue by SwapnilShahGit** [ABenchM/abm#60]
- [x] set up new version modal skeleton
- [x] fetch possible filters from hermes and populate modal (semi-existing code)
- [x] build version from the modal
- [x] select filters wanted for version
- [ ] search for filters
- [ ] run hermes after version is built with selected filters
- [ ] create a new filter for custom logic (at least X lines of code, Y number of commits, etc.)

**Comment by SwapnilShahGit** [comment]
From mockup for reference: <img width="451" alt="new_version" src="https://user-images.githubusercontent.com/11033960/36942052-0f55a6cc-1f38-11e8-8e71-f89b635d3b55.png">

**Comment by alexli123** [comment]
Initial implementation of this has been pushed into feat/54 branch. Refer to the list above for the outstanding items that need to be finished. Overall, the flow of the model should reflect the following:

1. Search for filters you may want to add
2. Select filters that you want to add
3. Click "Create Version" to build a new version and run the hermes filters on that version.

**Comment by ankur-1989** [comment]
@nguyenLisa 

Do we need this issue now?

**Comment by nguyenLisa** [comment]
No need for that, since we moved the filtering to Delphi. Closing.
