### ISSUE TITLE
implement “Make Public” button

### ISSUE THREAD

**Issue by SwapnilShahGit** [ABenchM/abm#65]
- use existing code

**Comment by SwapnilShahGit** [comment]
ensure you verify with the user with a popup

**Comment by tylerpav** [comment]
Make Public button displays this text in the console and does nothing (used existing code):
11:18:40.682 [qtp1831882653-59] DEBUG d.f.a.a.websocket.BuildStatusSocket - Looking for build c6c64696-53b9-4305-b9c2-4692c52dbed2
11:18:40.689 [qtp1831882653-59] DEBUG d.f.a.a.websocket.BuildStatusSocket - Looking for build 3d359934-2520-4eac-be6b-a09bd1a1e2c1
