### ISSUE TITLE
implement download results button

### ISSUE THREAD

**Issue by SwapnilShahGit** [ABenchM/abm#66]
- use existing code

**Comment by tylerpav** [comment]
can't seem to find the js/java methods for this - the old editCollection.htm has CollectionController.downloadCsv(version id) however that doesn't seem to actually exist.

**Comment by nguyenLisa** [comment]
The "Download Hermes Results" button (https://abm.cs.upb.de/abm/index.html#/view/c07f9a2d-cf33-4c74-b415-c127ae85632b) links to the rest API downloadHermes (https://github.com/ABenchM/abm/blob/master/bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/download/HermesHttpContext.java#L37)
Does that help?

**Comment by SwapnilShahGit** [comment]
The old implementation maps to another controller, "viewController". We need to replace the ng-click to vc.downloadHermes(cc.version.id).

**Comment by SwapnilShahGit** [comment]
It seemed messy to use another controller inside the "editcollection.htm" file, so I created a new method in "collectionController" that customizes the download collection for private repositories. However, I am having issues with the API. I have attached screenshots for reference below.
![image](https://user-images.githubusercontent.com/11033960/37867028-16d7b782-2f69-11e8-9e30-60bc4cdd586c.png)
![image](https://user-images.githubusercontent.com/11033960/37867029-1b9a82ea-2f69-11e8-88c0-64109a67238c.png)

@nguyenLisa @bhermann

**Comment by bhermann** [comment]
It seems like the API call is missing authentication. A private collection should only be visible to the appropriate authenticated user. As API calls are stateless you would need to provide valid authentication.

**Comment by bhermann** [comment]
You should also see more details in the server log.

**Comment by SwapnilShahGit** [comment]
I seem to be getting a different error without changing anything, are there any suggestions for this?
![image](https://user-images.githubusercontent.com/11033960/37878409-f9737c70-3036-11e8-84ae-154fc1f55b99.png)

**Comment by nguyenLisa** [comment]
Could you write down the steps to reproduce your error from the code in the master branch?

**Comment by SwapnilShahGit** [comment]
As an update here, I am in talks with Ankur to resolve this issue.

**Comment by ankur-1989** [comment]
I tried to reproduce the issue using feat/54 branch, but I did not get the issue. It was working fine for me.I did not see the buttons to build the collections so that I would have tested for new collections.

**Comment by SwapnilShahGit** [comment]
The cause of this issue was found and fixed. Closing!

**Comment by nguyenLisa** [comment]
By curiosity, what was it?

**Comment by SwapnilShahGit** [comment]
The current feat/54 branch does not have a Hermes build running and therefore could not download the results. The code for download results is properly implemented but could not find the results as there are none (logical overlooked from my behalf).
