### ISSUE TITLE
Implement build failing notification system

### ISSUE THREAD

**Issue by SwapnilShahGit** [ABenchM/abm#67]
- notify the user when one of the current builds fails

**Comment by SwapnilShahGit** [comment]
From mockup for reference: 
<img width="201" alt="build_failed_notification" src="https://user-images.githubusercontent.com/11033960/36942059-35a22648-1f38-11e8-8b6f-9caa8e29b123.png">

**Comment by SwapnilShahGit** [comment]
update a create slide bar for version build information

**Comment by ankur-1989** [comment]
@nguyenLisa 
Can we close this issue now? as this build functionality is not there anymore in ABM.
