### ISSUE TITLE
New bug has been introduced after changes in front end modal window of Build.

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm#79]
It does not show the correct status of the build.
Steps to reproduce the issue:- 
1. Create a collection and start building the collection using button build this version. 
2. Modal window will open and will show the status of the process.
3. It will keep running at a particular step feels like it is stuck but when you close the modal window and come back again it shows the actual status of the process.

**Comment by nguyenLisa** [comment]
Which commit introduced the bug?

**Comment by ankur-1989** [comment]
I can not comment about the commit but after shifting the modal window from left to right only problem has started.

**Comment by nguyenLisa** [comment]
Those are the two commits that modified the direction of the modal window: 4c14fa942f712ea9bc33e2d01a32098691236770 and 7729a0c782e20e919475f861c0459f4799d5f195
From a first glance, I don't see what in those commits would cause the issue. Could you look into it?

**Comment by ankur-1989** [comment]
ok I will check.

**Comment by ankur-1989** [comment]
working fine, therefore, closing the issue.
