### ISSUE TITLE
Title is out of focus on small screens

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm#8]
Modify layout for smaller screens so that the title on the top right does not overflow.

<img width="1278" alt="capture d ecran 2018-01-26 a 18 24 55" src="https://user-images.githubusercontent.com/1546847/35452268-5054b46c-02c6-11e8-9fa4-9f13476afb0b.png">

**Comment by nguyenLisa** [comment]
Any update on the bug we talked about? : For smaller screens, the title overlaps with the menu. Ideally, one should go below the other if the screen is resized and there is not enough space for both on the same line.

**Comment by nguyenLisa** [comment]
Also, on bigger screens, the title goes over the right margin. Could you please fix that?
![untitled](https://user-images.githubusercontent.com/1546847/36246013-0af71faa-122e-11e8-8b28-5dc41ea8027c.png)

**Comment by alexli123** [comment]
Hey Lisa, I missed any comments on this bug after I issued the pull request - I'll take care of this shortly.
