### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by nguyenLisa** [ABenchM/abm#9]
Make error messages more understandable. For the moment "Error 500" is not adapted for end-users.

**Comment by SwapnilShahGit** [comment]
Is there backend support for this issue?

**Comment by nguyenLisa** [comment]
What kind of backend support do you need?

**Comment by SwapnilShahGit** [comment]
As in, if the password is incorrect, does the backend let us know, or does it just send us an error 500?

**Comment by nguyenLisa** [comment]
As you can see in the code of the frontend controllers (de.fraunhofer.abm.app/web/controllers/), the backend already handles different kinds of errors. "Error 500" is the default code for when the backend generates an exception or communication errors between the backend and the frontend occur. 
For this issue, you simply need to make the messages that are shown in the notifications more user-friendly. For example, the user gains nothing in seeing that "Error 500" occured, nor that it comes from a database exception in the backend. Instead, they should know that the Collection could not be retrieved or that there was an error in running the filters.

**Comment by janniclas** [comment]
according to this pull request https://github.com/ABenchM/abm/pull/149 this issue should be fixed and therefore closed. Please reopen if it still exists.
