### ISSUE TITLE
Add headers to the Projects selected table in create collection UI

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm#92]
Add Headers to the "Projects selected" table that list all the Projects and other details.

**Comment by nguyenLisa** [comment]
Could you separate this issue into multiple ones for different features?
Also, please check whether or not some features have already been entered in the issue tracker before. For example, #91 for your third point.

**Comment by nguyenLisa** [comment]
Could you separate this issue into multiple ones for different features?
Also, please check whether or not some features have already been entered in the issue tracker before. For example, #91 for your third point.
And finally, please label the issues you are reporting.

**Comment by mac24079** [comment]
Done.

**Comment by nguyenLisa** [comment]
Thanks. Closing.

**Comment by mac24079** [comment]
Should we re-open this as instead of deleting this whole issue, I removed the other issues to new one, containing this to be a single issue. Or may be I can create a new issue for this ticket. #Add headers to the Projects selected table in create collection UI.
What you suggests as this issue 91 was also referred in comments of #91 ?

**Comment by nguyenLisa** [comment]
Please make that its own issue. In the future, please avoid modifying the issue descriptions for tracking purposes.

**Comment by mac24079** [comment]
OK.
