### ISSUE TITLE
Fix Responsive Layout 

### ISSUE THREAD

**Issue by janniclas** [ABenchM/abm#93]
When reducing the window size the layout is displayed incorrectly as seen in the following picture.

![image](https://user-images.githubusercontent.com/8062521/38781513-cf8b7492-40e6-11e8-8fdd-dbe52a61d156.png)

**Comment by nguyenLisa** [comment]
This was wanted (#8). If you see an improvement to make, please re-open that bug. Thanks!

**Comment by janniclas** [comment]
I was not talking about the Title moving into the second line, but the header overlapping with the content. 
This is the view when the content view is scrolled completely to the top, but still half the text is cut off. I believe this is a different issue than the one described in https://github.com/ABenchM/abm/issues/8, or am I mistaken?

**Comment by nguyenLisa** [comment]
I see. That's indeed a different issue. My bad.

**Comment by johannesduesing** [comment]
This issue has been moved to the new abm-frontend repository at https://github.com/ABenchM/abm-frontend/issues/22
