### ISSUE TITLE
Move action column (check-boxes) to the left of create collection UI

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm#95]
Move action column (checkbox etc.) to the left of the table for easy accessibility.

**Comment by nguyenLisa** [comment]
Why would it be more accessible on the left compared to the right?

**Comment by mac24079** [comment]
As per user it will look more aesthetic and as the UI is more aesthetic user is more willing to look forward.(It's just my opinion). Also, if the action columns appear on the left a user can easily select just after reading the name and description(even if it is long) of the project.
May be we can discuss this in the meeting.

**Comment by johannesduesing** [comment]
This issue has been moved to the new abm-frontend repository at https://github.com/ABenchM/abm-frontend/issues/23
