### ISSUE TITLE
Add headers to the "Projects selected" table in create collection UI

### ISSUE THREAD

**Issue by mac24079** [ABenchM/abm#99]
The table doesn't contains any header columns which should be added to the table displaying the Projects and other details in create collection UI.

**Comment by johannesduesing** [comment]
This issue has been moved to the new abm-frontend repository at https://github.com/ABenchM/abm-frontend/issues/25

**Comment by mac24079** [comment]
Fixed [94becbd523da7c64d6072acd47314163b20f0ad1](url)
